name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        python -m build

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          ## 🎉 新版本发布
          
          ### 📋 更新内容
          请查看 [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) 获取详细更新内容。
          
          ### 📦 安装方式
          ```bash
          pip install keynote-mcp
          ```
          
          ### 🔧 升级方式
          ```bash
          pip install --upgrade keynote-mcp
          ```
          
          ### 📚 文档
          - [使用文档](https://github.com/${{ github.repository }}/blob/main/README.md)
          - [API 文档](https://github.com/${{ github.repository }}/blob/main/docs/)
          - [示例代码](https://github.com/${{ github.repository }}/blob/main/examples/)

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/keynote-mcp-*.tar.gz
        asset_name: keynote-mcp-source.tar.gz
        asset_content_type: application/gzip

    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags/')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/* 